version: 1.0.{build}
build:
  verbosity: minimal

image: Visual Studio 2017

environment:
  matrix:
    - BUILD_TYPE: Release
      COMPILER: MSVC15
      PLATFORM: x64
    - BUILD_TYPE: Release
      COMPILER: MSVC15
      PLATFORM: Win32

cache:
- C:\projects\mpir
- C:\projects\mpfr
- C:\projects\pthreads
- C:\projects\flint2\mpir-2.7.2
- C:\projects\flint2\mpfr-3.1.5


build_script:
  - git submodule update --init
  - SET PYTHON=C:\Python36-x64
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - cd flint2

  - if [%COMPILER%]==[MSVC15] if not exist C:\projects\mpir .build_dependencies.cmd
  - if [%COMPILER%]==[MSVC15] if [%PLATFORM%]==[x64] set PATH=C:\Python35-x64;%PATH%
  - if [%COMPILER%]==[MSVC15] if [%PLATFORM%]==[Win32] set PATH=C:\Python35;%PATH%

  - if [%COMPILER%]==[MSVC15] call .appveyor_msvc_build.cmd
  
  # Move all built libraries into the "arb" folder so that CMake can detect them  
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - python rename_libs.py
  - ps: ls -r . | Out-File directories.txt
  - ps: appveyor PushArtifact (Get-Item -Path ".\directories.txt" -Verbose).FullName

  - cd "%APPVEYOR_BUILD_FOLDER%\arb"
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 15 2017 Win64"
  - cmake --build . --config Release                    # build
