version: 1.0.{build}
build:
  verbosity: minimal

image: Visual Studio 2017

environment:
  global:
    APPVEYOR_SAVE_CACHE_ON_ERROR: true
  matrix:
    - BUILD_TYPE: Release
      COMPILER: MSVC15
      PLATFORM: x64
    - BUILD_TYPE: Release
      COMPILER: MSVC15
      PLATFORM: Win32

cache:
  - '%LOCALAPPDATA%\pip\Cache'
  - 'C:\Tools\vcpkg\installed'
  - 'C:\Tools\vcpkg\packages'

build_script:
  # Now initialize the submodules 
  - git submodule update --init
  
  - ps: |
      git clone -q --branch=arblib https://github.com/xoviat/vcpkg.git
      cd vcpkg
      rm -r -Force C:\Tools\vcpkg\ports
      cp -r ports C:\Tools\vcpkg
      cd ..
      rm -r -Force vcpkg

  - vcpkg install arb:x64-windows-static

  - ps: ls -r . | Out-File directories.txt
  - ps: appveyor PushArtifact (Get-Item -Path ".\directories.txt" -Verbose).FullName
  
  # Now build the project
  - ps: |
      cd python-flint
      
      # Replace the "setup.py" with a patched version
      rm setup.py
      cp ..\project_setup.py .\setup.py
      
      $PYTHONS = @(
          ("C:\\Python35-x64"),
          ("C:\\Python36-x64")
      )
      
      mkdir dist      
      foreach ($PYTHON in $PYTHONS) {
          $env:PATH="$PYTHON;$PYTHON\Scripts;$env:PATH"

          python -m pip install -U pip setuptools wheel
          pip install cython

          $ARB_BUILD_DIR = "$env:APPVEYOR_BUILD_FOLDER\\arb\\build\\Release;$env:APPVEYOR_BUILD_FOLDER\\arb"
          $FLINT_BUILD_DIR = "$env:APPVEYOR_BUILD_FOLDER\\flint2\\lib\\$env:PLATFORM\\Release"
          $MPIR_BUILD_DIR = "$env:APPVEYOR_BUILD_FOLDER\\mpir\\lib\\$env:PLATFORM\\Release"
          $MPFR_BUILD_DIR = "$env:APPVEYOR_BUILD_FOLDER\\mpfr\\lib\\$env:PLATFORM\\Release"
          $PTHREADS_BUILD_DIR = "$env:APPVEYOR_BUILD_FOLDER\\pthreads\\lib\\$env:PLATFORM\\Release"

          python setup.py build_ext `
            "--include-dirs=$FLINT_BUILD_DIR;$ARB_BUILD_DIR;$MPIR_BUILD_DIR;$MPFR_BUILD_DIR;$PTHREADS_BUILD_DIR" `
            "--library-dirs=$FLINT_BUILD_DIR;$ARB_BUILD_DIR;$MPIR_BUILD_DIR;$MPFR_BUILD_DIR;$PTHREADS_BUILD_DIR"
            
          pip wheel . --wheel-dir=dist
          rm -r -Force build
      }

      ls dist -r | Foreach-Object {
          appveyor PushArtifact $_.FullName
      }
